[package]
name = "rly-gui"
version = "0.0.2"
authors = ["Michael Borejdo <mborejdo@gmail.com>"]
edition = "2021"

[dependencies]
yew = "0.17.3"
serde_urlencoded = "0.6.1"
serde_derive = "1.0.115"
anyhow = "1.0.32"