[package]
name = "rly-cli"
version = "0.0.1"
authors = ["Michael Borejdo <mborejdo@gmail.com>"]
edition = "2021"

[dependencies]
clap = "3.0.0-beta.1"
reqwest = { version = "0.10", features = ["json"] }
tokio = { version = "0.2", features = ["full"] }